Repository MIT-Emerging-Talent/2024-group-05-08-cdsp, pull requests merged in 2024-02, with the labels that each got.

#6 Challenges In Literacy Rate
  .github/ISSUE_TEMPLATE/help_wanted.md
Labels: documentation

#20 Retrospective lotfullah
  .DS_Store
  README.md
  milestone/milestone-2/data-cleaning.md
  milestone/milestone-2/dataset-documentation.md
  milestone/milestone-3/data-analysis.md
  retrospective/retrospective-1.md
  retrospective/retrospective-2.md
  retrospective/retrospective-3.md
Labels: documentation

#19 milestone-3 folder added
  .DS_Store
  retrospective/retrospective-1.md
  retrospective/retrospective-2.md
  retrospective/retrospective-3.md
Labels: help wanted

#25 Data cleaning
  .DS_Store
  README.md
  milestone/.DS_Store
  milestone/milestone-2/attendence_rate.ipynb
  milestone/milestone-2/data-cleaning.md
  milestone/milestone-2/literacy_rate.csv
  milestone/milestone-2/literacy_rate.ipynb
  milestone/milestone-2/school_age_digital_connectivity.ipynb
  retrospective/retrospective-2.md
Labels: documentation

#30 Update README.md
  README.md
Labels: documentation

#32 update to readme.md
  README.md
Labels: documentation

#29 Adding my retrospective.
  retrospective/retrospective-3.md
Labels: documentation

#28 Retrospective3-AliSina
  retrospective/retrospective-3.md
Labels: documentation

#38 Update README.md
  README.md
Labels: documentation

#44 Heading one is added.
  README.md
  data_source/cleaned_data/Completion_Rate.csv
  data_source/cleaned_data/Literacy_Rate.csv
  data_source/cleaned_data/Out_Of_School_Rate.csv
  data_source/cleaned_data/attendence_rate.csv
  milestone/milestone-2/Attendance_Rate.ipynb
Labels: documentation

#69 readme files updated
  data_source/README.md
  data_source/cleaning_progress/README.md
Labels: documentation

#65 tasabeeh learning goals added
  .collaboration/learning_goals.md
Labels: documentation

#62 Update README.md
  data_source/cleaned_data/README.md
Labels: bug, documentation

#66 readme file updated in Collaboration folder
  .collaboration/README.md
Labels: documentation

#83 Folders structuring
  data_source/cleaning_progress/README.md
  data_source/raw_data/.DS_Store
  data_source/raw_data/Adjusted_net_attendance_rate- Primary.csv
  data_source/raw_data/Attendance_Rate/Attendance_Rate.csv
  data_source/raw_data/Attendance_Rate/README.md
  data_source/raw_data/Completion_Rate/Completion_Rate.csv
  data_source/raw_data/Completion_Rate/README.md
  data_source/raw_data/GDP/README.md
  data_source/raw_data/GDP/gdp.csv
  data_source/raw_data/GDP_Expenditure/Government expenditure on education, total.csv
  data_source/raw_data/GDP_Expenditure/README.md
  data_source/raw_data/ICT_Skills/ICT-Skills_2022- Totals.csv
  data_source/raw_data/ICT_Skills/README.md
  data_source/raw_data/Literacy_Rate/Literacy_rate.csv
  data_source/raw_data/Literacy_Rate/README.md
  data_source/raw_data/Out_Of_School_Rate/OutofSchoolRate_CleanedDF.csv
  data_source/raw_data/Out_Of_School_Rate/README.md
  data_source/raw_data/School_Age_Digital_Connectivity/README.md
  data_source/raw_data/School_Age_Digital_Connectivity/School-Age-Digital-Connectivity.xlsx
Labels: documentation, enhancement

#89 Added table for variable names
  data_source/README.md
Labels: documentation
